itech_cw_group_17/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from salonrate import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='homepage'),
    path('salonrate/', include('salonrate.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

salonrate/urls.py
from django.urls import path
from salonrate import views

app_name = 'salonrate'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('salon/<slug:salon_name_slug>/', views.salon_detail, name="salon"),
    path('service/<slug:service_name_slug>/', views.service_detail, name="service"),
    path('search_result/', views.search_result, name='search_result'),
    path('ajax_search/', views.ajax_search, name='ajax_search'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

salonrate/models.py
from email.policy import default
import uuid
from django.db import models
from django.forms import CharField, FloatField, IntegerField
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.


class Salon(models.Model):
    salon_id = models.AutoField(primary_key=True, null=False)
    salon_name = models.CharField(max_length=50, null=False)
    salon_address = models.CharField(max_length=100, null=False)
    rate = models.FloatField(null=False, default=0.0)
    salon_avg_price = models.FloatField(default=0.0)
    salon_busy = models.BooleanField(default=False)
    image = models.ImageField(default="salon_image/default.jpg", upload_to="salon_image", blank=True)
    # tag = models.CharField(max_length=16, default='0')
    phone = models.CharField(max_length=16)
    open_time = models.CharField(max_length=32, default='10:00am-5:00pm')
    slug = models.SlugField(blank=True)
    good_env = models.BooleanField(default=False)
    good_service = models.BooleanField(default=False)
    cost_effective = models.BooleanField(default=False)
    good_skill = models.BooleanField(default=False)
    good_attitude = models.BooleanField(default=False)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.salon_name)
        super(Salon, self).save(*args, **kwargs)

    def __str__(self):
        return self.salon_name


class Service(models.Model):
    service_id = models.AutoField(primary_key=True, null=False)
    salon_id = models.ForeignKey(Salon, on_delete=models.CASCADE)
    service_name = models.CharField(max_length=50, null=False)
    service_type = models.IntegerField(default=0)
    service_price = models.FloatField(default=0.0)
    rate = models.FloatField(default=0.0)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.service_name) + "-" + str(self.service_id)
        super(Service, self).save(*args, **kwargs)

    def __str__(self):
        return self.service_name


class Comment(models.Model):
    comment_id = models.AutoField(primary_key=True, null=False)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    #salon_id = models.ForeignKey(Salon, on_delete=models.CASCADE)
    #service_id = models.ForeignKey(Service, on_delete=models.CASCADE)
    salon_or_service_id = models.IntegerField(default=0, null=False)
    type = models.IntegerField(default=0)
    comment = models.CharField(max_length=500)
    star = models.IntegerField(default=0, validators=[MaxValueValidator(5), MinValueValidator(0)])
    tag_environ = models.BooleanField(default=False)
    tag_service = models.BooleanField(default=False)
    tag_cost = models.BooleanField(default=False)
    tag_skill = models.BooleanField(default=False)
    tag_attitude = models.BooleanField(default=False)
    comment_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.comment_id)


class Follows(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    salon_id = models.ForeignKey(Salon, on_delete=models.CASCADE)

    def __str__(self):
        return self.username.username + self.salon_id.salon_name

    class Meta:
        verbose_name_plural = 'Follows'


class UserProfile(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default="profile_image/default.jpg", upload_to='profile_image', blank=True)

    def __str__(self):
        return self.user.username

salonrate/forms.py
from django import forms
from django.contrib.auth.models import User
from salonrate.models import UserProfile, Comment


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar', )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment', 'star', 'tag_environ', 'tag_service', 'tag_cost', 'tag_skill', 'tag_attitude', )

salonrate/views.py
from django.shortcuts import get_object_or_404, render, redirect
from salonrate.models import UserProfile, Salon, Service, Comment, Follows
from django.core import serializers
from salonrate.forms import CommentForm, UserForm, UserProfileForm
from django.urls import reverse
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.db.models import Q
from django.template.loader import render_to_string
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def register(request):
    # Set a boolean value to indicate the registration state.
    registered = False

    # If receiving a 'POST' request, register
    if request.method == 'POST':
        # Acquire information entered by the user
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        # If two forms are valid, register this user
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            # If user upload a picture for avatar, get it from the request
            if 'avatar' in request.FILES:
                profile.avatar = request.FILES['avatar']
            # Save profile
            profile.save()
            # Set registered to True
            registered = True
        else:
            # If two forms are invalid, print the errors
            print(user_form.errors, profile_form.errors)

    else:
        # If not a POST request, simply show the forms
        user_form = UserForm()
        profile_form = UserProfileForm()

    context_dict = {'user_form': user_form, 'profile_form': profile_form, 'registered': registered}
    return render(request, 'salonrate/register.html', context=context_dict)


def user_login(request):
    # If receiving a 'POST' request, check whether the user can log in
    if request.method == 'POST':
        # Acquire the messages entered by the user
        username = request.POST.get('username')
        password = request.POST.get('password')
        # Check whether this user is authenticated
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('salonrate:homepage'))
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        # If not a POST request, go to the login page
        return render(request, 'salonrate/login.html')


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('salonrate:homepage'))


@login_required
def user_profile(request):
    # If receiving a 'POST' request, upload avatar 
    if request.method == 'POST' and request.FILES:
        file = request.FILES['profile_picture']
        if file:
            profile = UserProfile.objects.filter(user=request.user)[0]
            profile.avatar=file
            profile.save()
    user = request.user
    profile = UserProfile.objects.filter(user=user)[0]
    follows = Follows.objects.filter(username=user)
    context_dic = {
        'username': request.user.username,
        'profile': profile,
        'follows': follows
    }

    comments_objs = Comment.objects.filter(username=user)
    comments = []
    # Combine comments with salon and service info
    for comment in comments_objs:
        type = comment.type
        id = comment.salon_or_service_id
        comment_dic = {}
        if (type == 0):
            salon = Salon.objects.filter(salon_id=id)[0]
        else:
            service = Service.objects.filter(service_id=id)[0]
            salon = Salon.objects.filter(salon_id=service.salon_id.salon_id)[0]
            comment_dic['service'] = service
        comment_dic['salon'] = salon
        comment_dic['comment'] = comment
        comments.append(comment_dic)
    context_dic['comments'] = comments
    return render(request, 'salonrate/userprofile.html', context_dic)

def homepage(request):
    """
    Homepage function which renders the homepage.html page
    :param request: request from page
    :return:  {request, homepage.html, {'salons': salons, 'salon1': salons[0], 'salon2': salons[1], 'salon3': salons[2]} }
    """
    # Randomly select three salons whose rate is larger equal than 3
    sql = "SELECT * FROM salonrate_salon WHERE rate >=3 ORDER BY random() LIMIT 3"
    salons = Salon.objects.raw(sql)
    context_dict = {"salons": salons, 'salon1': salons[0], 'salon2': salons[1], 'salon3': salons[2]}
    return render(request, 'salonrate/homepage.html', context_dict)

def refresh_salon(salon, comments):
    """
    Refresh_salon function which calculates the rate of salon and switch the status of tags based on comments
    :param salon and comments object
    :return:  refreshed salon object
    """
    if comments:
        salon.rate = round(sum([c.star for c in comments]) / len(comments))
        salon.save()
    else:
        salon.rate = 0
        salon.save()
    for comment in comments:
        if comment.tag_environ == True:
            salon.good_env = True
        if comment.tag_service == True:
            salon.good_service = True
        if comment.tag_cost == True:
            salon.cost_effective = True
        if comment.tag_skill == True:
            salon.good_skill = True
        if comment.tag_attitude == True:
            salon.good_attitude = True
        salon.save()
    return salon

def refresh_service(service, comments):
    """
    Refresh_service function which calculates the rate of service based on comments
    :param service and comments object
    :return:  refreshed service object
    """
    if comments:
        service.rate = round(sum([c.star for c in comments]) / len(comments))
        service.save()
    else:
        service.rate = 0
        service.save()
    return service

def salon_detail(request, salon_name_slug="rich-hair-beauty-salon"):
    """
    Salon_detail function which renders the salon.html page, handles get and post requests and identifies them for further process
    :param request: request from page
    :return:  {request, salon.html, {'salon': salon, 'services': services, 'comments':comments, 'comment_count':comment_count, 'follow': follow} }
    """
    salon = get_object_or_404(Salon, slug=salon_name_slug)
    comments = Comment.objects.filter(salon_or_service_id=salon.salon_id, type=0).order_by("-comment_id")
    services = Service.objects.filter(salon_id=salon.salon_id).order_by("-service_id")
    salon = refresh_salon(salon, comments)
    context_dict = {"salon": salon, "services": None, "comments": comments, "follow": False}
    # if comment exists, return comment_count
    if comments:
        context_dict["comment_count"] = len(comments)
    else:
        print("No Comments")
        
    # If there are services under the salon, return services
    if services:
        context_dict["services"] = services
    else:
        print("No services available yet")

    # If user is authenticated, return the follow state
    if request.user.is_authenticated:
        follows = Follows.objects.filter(username=request.user)
        for follow in follows:
            if follow.salon_id == salon:
                context_dict["follow"] = True

    commentform = CommentForm()
    if request.method == 'POST':
        # If there is comment in the request data, submit the commentForm
        if 'comment' in request.POST:
            commentform = CommentForm(request.POST)
            if commentform.is_valid():
                comment = commentform.save(commit=False)
                comment.username = request.user
                comment.salon_or_service_id = salon.salon_id
                comment.type = 0
                comment.save()
                salon = refresh_salon(salon, comments)
                context_dict["salon"] = salon
            return redirect(reverse("salonrate:salon", kwargs={"salon_name_slug": salon_name_slug}))
        
        # If there is no comment, submit the followForm
        else:
            print('followForm detected')
            if context_dict["follow"] == True:
                follows = Follows.objects.filter(username=request.user, salon_id=salon)
                for f in follows:
                    f.delete()
                print('follow deleted')
            else:
                follow = Follows(username=request.user, salon_id=salon)
                follow.save()
                print('follow saved')
            return redirect(reverse("salonrate:salon", kwargs={"salon_name_slug": salon_name_slug}))
    context_dict['form'] = commentform
    return render(request, 'salonrate/salon.html', context_dict)


def service_detail(request, service_name_slug="eyebrows-eyelashes-191"):
    """
    Service_detail function which renders the service.html page, handles get and post requests and identifies them for further process
    :param request: request from page
    :return:  {request, service.html, {'service': service, 'comments':comments, 'comment_count':comment_count}
    """
    service = get_object_or_404(Service, slug=service_name_slug)
    comments = Comment.objects.filter(salon_or_service_id=service.service_id, type=1).order_by("-comment_id")
    service = refresh_service(service, comments)
    context_dict = {"service": service, "comments": comments}
    
    if comments:
        context_dict["comment_count"] = len(comments)

    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)

        print(form)

templates/salonrate/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
    <meta charset="UTF-8">
    <title>
        Salonrate -{% block title_block %}Welcome to the Salonrate!{% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="https://s1.pstatp.com/cdn/expire-1-M/font-awesome/4.6.0/css/font-awesome.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/base.css" />
    {% block css_block %}
    {% endblock %}
</head>

<body>
<div class="result-header">
    <a href="{% url 'salonrate:homepage' %}"><img class="logo-img" src="{% static 'images/logo.png' %}"
                                                alt="Salonrate Logo"></a>
    <div class="search-box">
        <ul class="search-switch" id="test">
            <li class="selected">Salon</li>
            <li>Service</li>
        </ul>
        <form id="search-form" action='{% url "salonrate:search_result" %}' method="post">
            {% csrf_token %}
            <div class="search-area">
                <label>
                    <input class="dynamic-scope" name="scope" hidden value="salon">
                    <input class="search-txt" type="text" placeholder="Search for salon or service" name="keyword">
                </label>
                <a class="search-btn" type="submit">
                    <img class="search-img" src="{% static 'images/search.png' %}" alt="Q">
                </a>
            </div>
        </form>
    </div>
    <div class="my-center">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                {% if user.is_authenticated %}
                    {% if user.userprofile.avatar %}
                        {% if user.userprofile.avatar.url %}
                        <img class='me-img' src="{{ user.userprofile.avatar.url }}" alt="Avatar" />
                        {% endif %}
                    {% else %}
                    <img class="me-img" src="{% static 'images/me.png' %}" alt="My logo">
                    {% endif %}
                    <a>{{ user.username }}</a>
                {% else %}
                    <img class="me-img" src="{% static 'images/me.png' %}" alt="My logo">
                    <a>My Account</a>
                {% endif %}
            </a>
            <ul class="dropdown-menu">
                {% if user.is_authenticated %}
                <li class="menu"><a href="{% url 'salonrate:logout' %}">Logout</a></li>
                <li class="menu"><a href="{% url 'salonrate:profile' %}">Profile</a> </li>
                {% else %}
                <li class="menu"><a href="{% url 'salonrate:login' %}">Login</a></li>
                <li class="menu"><a href="{% url 'salonrate:register' %}">Register</a></li>
                {% endif %}
            </ul>
        </li>
    </div>
</div>
<hr/>
<div class="main">
    {% block body_block %}
    {% endblock %}
</div>
<div class="about">
    <hr/>
    <dl>
        <dt>· About Us: IT-17 ·</dt>
        <br />
        <dd>2589587C · Cui, Chong</li>
        <dd>2647735Y · Ying, Heting</li>
        <dd>2590260Y · Yang, Suiyi</li>
        <dd>2612713X · Xiong, Yipeng</li>
        <dd>2492428V · Varadhan, Reetu Thillai</li>
    </dl>
</div>
</body>
</html>

templates/salonrate/salon.html
{% extends 'salonrate/base.html' %}
{% load staticfiles %}

{% block css_block %}
<link rel="stylesheet" type="text/css" href="/static/css/salon.css" />
{% endblock %}

{% block title_block %}
    Salon Detail
{% endblock %}

{% block body_block %}
<div class="main">
    <div class="detail">
        <div class="left">
            <div class="name">
                <h2>{{ salon.salon_name }}</h2>
                {% if user.is_authenticated %}
                    {% if follow %}
                    <div class="f">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input class="f1" type="submit" value="Unfollow">
                        </form>
                        <label class="followed"></label>
                    </div>
                    {% else %}
                    <div class="f">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input class="f2" type="submit" value="Follow">
                        </form>
                        <label class="unfollowed"></label>
                    </div>
                    {% endif %}
                {% else %}
                    <div class="f">
                        <a href="{% url 'salonrate:login' %}"><input class="f2" value="Follow"></a>
                        <a href="{% url 'salonrate:login' %}"><label class="unfollowed"></label></a>
                    </div>
                {% endif %}
            </div>
            <div class="comline">
                <div class="item-rate">
                    <fieldset>
                        {% if salon.rate > 4 %}
                        <label class="star4 rated" title="Outstanding">5 stars</label>
                        {% else %}
                        <label class="star4" title="Outstanding">5 stars</label>
                        {% endif %}

                        {% if salon.rate > 3 %}
                        <label class="star3 rated" title="Very Good">4 stars</label>
                        {% else %}
                        <label class="star3" title="Very Good">4 stars</label>
                        {% endif %}

                        {% if salon.rate > 2 %}
                        <label class="star2 rated" title="Good">3 stars</label>
                        {% else %}
                        <label class="star2" title="Good">3 stars</label>
                        {% endif %}

                        {% if salon.rate > 1 %}
                        <label class="star1 rated" title="Poor">2 stars</label>
                        {% else %}
                        <label class="star1" title="Poor">2 stars</label>
                        {% endif %}

                        {% if salon.rate > 0 %}
                        <label class="star0 rated" title="Very Poor">1 star</label>
                        {% else %}
                        <label class="star0" title="Very Poor">1 star</label>
                        {% endif %}
                    </fieldset>
                </div>            
                <div class="comcount">
                    {{ comment_count }} 
                    {% if comment_count == 1 %}
                    Comment
                    {% else %}
                    Comments
                    {% endif %}
                </div>
            </div>
            <div class="price"><label class="fa-money"></label> Average Cost: £ {{ salon.salon_avg_price }}</div>
            <div class="contact"><label class="fa-phone-square"></label> Phone: {{ salon.phone }}</div>
            <div class="open"><label class="fa-clock-o"></label> Opening Hours: {{ salon.open_time }}</div>
            <div class="address"><label class="fa-map-marker"></label> {{ salon.salon_address }}</div>
            <ul class="item-tags">
                <ul class="tags">
                    {% if salon.good_env %}
                    <li id="tags">Nice Environment</li>
                    {% endif %}
                    {% if salon.good_service %}
                    <li id="tags">Attentive Service</li>
                    {% endif %}
                    {% if salon.cost_effective %}
                    <li id="tags">Cost Effective</li>
                    {% endif %}
                    {% if salon.good_skill %}
                    <li id="tags">Excellent Skill</li>
                    {% endif %}
                    {% if salon.good_attitude %}
                    <li id="tags">Warm Attidute</li>
                    {% endif %}
                </ul><br />
            </ul>
        </div>
        <div class="right">
            {% if salon.image %}
            <img class="promopic" src="{{ salon.image.url }}" alt="salon_img" />
            {% else %}
            <img class="promopic" src="{% static 'images/salondefault.jpeg' %}" alt="salon_img" />
            {% endif %}
        </div>
    </div>
    <hr />
    <div class="services">
        <h4>· Services Offered ·</h4>
        {% if services %}
        <div class="container">
            <div class="row row-cols-auto">
                {% for service in services %}
                <div class="col-lg-auto">
                    <a href="{% url 'salonrate:service' service.slug %}">
                        <div class="service-item">
                            <div class="service_img">
                                {% if service.service_type == 0 %}
                                <img class="sp" src="{% static 'images/wash.png' %}" alt="wash_img" />
                                {% elif service.service_type == 1 %}
                                <img class="sp" src="{% static 'images/cut.jpeg' %}" alt="cut_img" />
                                {% elif service.service_type == 2 %}
                                <img class="sp" src="{% static 'images/dye.jpeg' %}" alt="dye_img" />
                                {% elif service.service_type == 3 %}
                                <img class="sp" src="{% static 'images/perm.jpg' %}" alt="perm_img" />
                                {% elif service.service_type == 4 %}
                                <img class="sp" src="{% static 'images/care.jpeg' %}" alt="care_img" />
                                {% else %}
                                <img class="sp" src="{% static 'images/item.png' %}" alt="care_img" />
                                {% endif %}
                            </div>
                            <div class="service_info">
                                <div class="service_name">{{ service.service_name }}</div>
                                <div class="service_price">£{{ service.service_price }}</div>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>
    <div class="comment">
        <div class="subtopic">
            <h4>· Comments On Salon ·</h4>
            {% if user.is_authenticated %}
            <button class="mac" id="mac">Write a Comment</button>
            {% else %}
                <a href="{% url 'salonrate:login' %}"><button class="cl">Log in to write a comment</button></a>
            {% endif %}
        </div>
        <form id="commentForm" class="cmf" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="star-rate">
                <fieldset>
                    <label class="star4" title="Outstanding">5</label>
                    <label class="star3" title="Very Good">4</label>
                    <label class="star2" title="Good">3</label>
                    <label class="star1" title="Poor">2</label>
                    <label class="star0" title="Very Poor">1</label>
                </fieldset>
            </div>
            <p style="display: none" name="star" id="id_star">{{ form.star.label }}{{ form.star }}</p>
            <input type="checkbox" name="tag_environ" id="id_tag_environ">
            <label for="id_tag_environ" name="tag_environ">Nice Environment</label>
            
            <input type="checkbox" name="tag_service" id="id_tag_service">
            <label for="id_tag_service" name="tag_service">Attentive Service</label>
            
            <input type="checkbox" name="tag_cost" id="id_tag_cost">
            <label for="id_tag_cost" name="tag_cost">Cost Effective</label>
            
            <input type="checkbox" name="tag_skill" id="id_tag_skill">
            <label for="id_tag_skill" name="tag_skill">Excellent Skill</label>
            
            <input type="checkbox" name="tag_attitude" id="id_tag_attitude">
            <label for="id_tag_attitude" name="tag_attitude">Warm Attidute</label><br />
        
            <textarea type="text" name="comment" maxlength="500" required id="id_comment" placeholder="Enter your comment here. No more than 500 letters." ></textarea><br />
            <input class="submit1" type="submit" value="Submit" id="commentForm"/>
            <input class="submit2" type="button" value="Cancel" id="cancel" />
        </form>
        {% if comments %}
        {% for comment in comments %}
        <div class="comment-item">
            {% if comment.username.userprofile.avatar %}
            <div class="avatar"><img class='ava' src="{{ comment.username.userprofile.avatar.url }}" alt="Avatar" /></div>
            {% else %}
            <div class="avatar"><img class='ava' src="{% static 'images/me.png' %}" alt="Avatar" /></div>
            {% endif %}
            <div class="comright">
                <div class="user">{{ comment.username.username }}</div><br />
                <div class="item-rate">
                    <fieldset>
                        {% if comment.star > 4 %}
                        <label class="star4 rated" title="Outstanding">5 stars</label>
                        {% else %}
                        <label class="star4" title="Outstanding">5 stars</label>
                        {% endif %}

                        {% if comment.star > 3 %}
                        <label class="star3 rated" title="Very Good">4 stars</label>
                        {% else %}
                        <label class="star3" title="Very Good">4 stars</label>
                        {% endif %}

                        {% if comment.star > 2 %}
                        <label class="star2 rated" title="Good">3 stars</label>
                        {% else %}
                        <label class="star2" title="Good">3 stars</label>
                        {% endif %}

                        {% if comment.star > 1 %}
                        <label class="star1 rated" title="Poor">2 stars</label>
                        {% else %}
                        <label class="star1" title="Poor">2 stars</label>
                        {% endif %}

                        {% if comment.star > 0 %}
                        <label class="star0 rated" title="Very Poor">1 star</label>
                        {% else %}
                        <label class="star0" title="Very Poor">1 star</label>
                        {% endif %}
                    </fieldset>
                </div>
                <div class="content">{{ comment.comment }}</div><br />
                <ul class="tags">
                    {% if comment.tag_environ %}
                    <li id="tags">Nice Environment</li>
                    {% endif %}
                    {% if comment.tag_service %}
                    <li id="tags">Attentive Service</li>
                    {% endif %}
                    {% if comment.tag_cost %}
                    <li id="tags">Cost Effective</li>
                    {% endif %}
                    {% if comment.tag_skill %}
                    <li id="tags">Excellent Skill</li>
                    {% endif %}
                    {% if comment.tag_attitude %}
                    <li id="tags">Warm Attidute</li>
                    {% endif %}
                </ul><br />
                <div class="datetime"> {{ comment.comment_time }}</div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="remind">Still waiting for the first comment~</div>
        {% endif %}
    </div>
</div>
<script src="{% static 'js/salon.js' %}" crossorigin="anonymous"></script>
{% endblock %}